# -*- coding: utf-8 -*-
"""Dataprep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7kGj1FKMgPVDcN77IYUexMbncN_DloS
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')
df_glucose = pd.read_csv("/content/drive/MyDrive/Glucose studies/glucose_insulin_ICU.csv")
df_demographic=pd.read_csv("/content/drive/MyDrive/Glucose studies/ADMISSIONS.csv")
df_patients=pd.read_csv("/content/drive/MyDrive/Glucose studies/PATIENTS.csv")

df_diag = pd.read_csv("/content/drive/MyDrive/Glucose studies/DIAGNOSES_ICD.csv")
septic_diag=['67020','67022','67024','77181','11403','99592','67030','67032','67034','31','545','380','3810','3811','3812','3819','382','383','3840','3841','3842','3843','3844','3849','388','389','202','223','449','41512','42292','65930','65931','65933','77181','99591','99592','99802','78552']
sepsis = df_diag[df_diag['ICD9_CODE'].isin(septic_diag)]

a=sepsis['SUBJECT_ID']
merged_df=df_glucose[df_glucose['SUBJECT_ID'].isin(a)]

merged_df = pd.merge(merged_df, df_demographic, on='HADM_ID')

merged_df = merged_df.rename(columns={'SUBJECT_ID_x': 'SUBJECT_ID'})

merged_df = pd.merge(merged_df, df_patients, on='SUBJECT_ID')

merged_df['Admit_time_str']=merged_df['ADMITTIME'].str.slice(start=0, stop=4)
merged_df['Admit_time_int']=pd.to_numeric(merged_df['Admit_time_str'])

merged_df['DOB_str']=merged_df['DOB'].str.slice(start=0, stop=4)
merged_df['DOB_int']=pd.to_numeric(merged_df['DOB_str'])

df_ICUStay=pd.read_csv("/content/drive/MyDrive/Glucose studies/ICUSTAYS.csv")
merged_df = pd.merge(df_ICUStay, merged_df, on='ICUSTAY_ID')

merged_df['MinCurr']=(pd.to_numeric(merged_df['OUTTIME'].str.slice(start=0, stop=4)))*365*12*29.5*24*60
merged_df['MinCurr']=merged_df['MinCurr']+(pd.to_numeric((merged_df['OUTTIME'].str.slice(start=6, stop=7)))*29.5*24*60)
merged_df['MinCurr']=merged_df['MinCurr']+(pd.to_numeric((merged_df['OUTTIME'].str.slice(start=9, stop=10)))*24*60)
merged_df['MinCurr']=merged_df['MinCurr']+(pd.to_numeric((merged_df['OUTTIME'].str.slice(start=12, stop=13)))*60)
merged_df['MinCurr']=merged_df['MinCurr']+(pd.to_numeric((merged_df['OUTTIME'].str.slice(start=15, stop=16))))

merged_df['MinAdm']=(pd.to_numeric(merged_df['INTIME'].str.slice(start=0, stop=4)))*365*12*29.5*24*60
merged_df['MinAdm']=merged_df['MinAdm']+(pd.to_numeric((merged_df['INTIME'].str.slice(start=6, stop=7)))*29.5*24*60)
merged_df['MinAdm']=merged_df['MinAdm']+(pd.to_numeric((merged_df['INTIME'].str.slice(start=9, stop=10)))*24*60)
merged_df['MinAdm']=merged_df['MinAdm']+(pd.to_numeric((merged_df['INTIME'].str.slice(start=12, stop=13)))*60)
merged_df['MinAdm']=merged_df['MinAdm']+(pd.to_numeric((merged_df['INTIME'].str.slice(start=15, stop=16))))

merged_df['minutesPassed']=merged_df['MinCurr']-merged_df['MinAdm']

import numpy as np

merged_df['minutesPassed']

merged_df['daysPassed']=(merged_df['minutesPassed']/60/24)
merged_df['daysPassed']=np.ceil(merged_df['daysPassed'])

merged_df['daysPassed']

merged_df['age']=merged_df['Admit_time_int']-merged_df['DOB_int']

data_include=merged_df[merged_df.age>18]

data_include=data_include[data_include.ETHNICITY!='UNKNOWN/NOT SPECIFIED']
data_include=data_include[data_include.ETHNICITY!='OTHER']
data_include=data_include[data_include.ETHNICITY!='PATIENT DECLINED TO ANSWER']
data_include=data_include[data_include.ETHNICITY!='UNABLE TO OBTAIN']

data_include=data_include[data_include.LOS_ICU_days>1]
print(len(data_include))

data_include.head()

len(data_include)

data_include.to_csv('data.csv', index=False)
from google.colab import files

files.download('data.csv')