# -*- coding: utf-8 -*-
"""cohortSelection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTbSDAPkjEDMUIwjArYLksIZyLe9YB41
"""

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

from google.cloud import bigquery
import pandas as pd

!pip install google-cloud-bigquery


df = pd.io.gbq.read_gbq('''
  SELECT *
  FROM `glucosedatabyicu.mergingFiltering.comb`
''', project_id='glucosedatabyicu')

df.head()

ageTrim=df[df['age']>18]
print(f"After removing those 18 or younger: {len(ageTrim)}")

sepTrim=ageTrim[ageTrim['sepsis3']==1]
print(f"After removing those without sepsis:{len(sepTrim)}")

losTrim=sepTrim[sepTrim['los']>1]
print(f"After removing those who stayed less than 1 day:{len(losTrim)}")

race=losTrim[losTrim['race_group']!='OTHER']
race=race[race['race_group']!='Other']
print(f"After removing those who stayed less than 1 day:{len(race)}")

from google.colab import files

# Save DataFrame to a CSV file
race.to_csv('cohortedData.csv', index=False)

# Download the CSV file
files.download('cohortedData.csv')