# -*- coding: utf-8 -*-
"""dataVisualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YC4zlz17INRnv8qSYOTpKs6ZeJpxgEPn
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv("/content/drive/MyDrive/Glucose-Research/preparedData.csv")

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
# %matplotlib inline
try:
    from tableone import TableOne, load_dataset
except (ModuleNotFoundError, ImportError):
    # install on Colab
    !pip install tableone
    from tableone import TableOne, load_dataset

gludata = pd.read_csv("/content/drive/MyDrive/Glucose studies/alldays_tableone.csv")

gludata.head()
gludata=gludata[gludata['RACE']!='Other']

gludata.head()

columns = ['LOS_ICU_days','RACE','GENDER','age','avg_gluc_day1', 'avg_gluc_day2', 'avg_gluc_day3','avg_gluc_day4','avg_gluc_day5','avg_gluc_day6','avg_gluc_day7','avg_gluc_day8','avg_gluc_day9','avg_freq_day1','avg_freq_day2','avg_freq_day3','avg_freq_day4','avg_freq_day5','avg_freq_day6','avg_freq_day7','avg_freq_day8','avg_freq_day9']
groupby = ['RACE']

mytable = TableOne(gludata, columns=columns, groupby=groupby, pval=False)

print(mytable.tabulate(tablefmt = "fancy_grid"))
